### ISSUE TITLE
SnSnEd closes SnipSniper as a whole

### ISSUE THREAD

**Issue by KiwiKaiser** [CaptureCoop/SnipSniper#74] opened 2021-09-16 16:11 UTC
When closing SnSnEd in the standalone Modus using "X" the complete program closes/crashes. Does not happen when SnSnEd is opened after taking a screenshot. Does also not happen when using right-click to close the editor.

**Comment by SvenWollinger** [comment] 2021-09-16 16:38
Its suposed to close when you press the X, no?
I dont quite understand the issue.
If you open the editor in the standalone version you get ONE editor window and when you close it it stops.
What do you want as the intended behaviour?

**Comment by KiwiKaiser** [comment] 2021-09-16 16:49
It should only close the editor, not stop Snipsniper running. (With the all
of Snipsniper I mean that even the taskbar icons disappeares. Haven't
checked if the service is still running)

SvenWollinger ***@***.***> schrieb am Do., 16. Sept. 2021,
18:38:

**Comment by SvenWollinger** [comment] 2021-09-16 18:23
The standalone editor does not start SnipSniper itself, only the editor.
The icons on the task tray *never* appear when you launch the Standalone Editor.
That is intended, when you launch the Editor Standalone no profiles ever get loaded.

**Comment by KiwiKaiser** [comment] 2021-09-16 19:49
Of cause no taskbar tray appears when you start SnSnEd standalone
(Standalone in means that it is opened without haven taken a screenshot
before, not in means you have started SnSnEd without a running SnSn session
of cause) The problem is that if you start the editor via right clicking at
a profile tray in the taskbar and close the editor window afterwards using
X, not only the editor window closes but also the tray icons of the
generally running SnSn session disappears. You need to manually Start snsn
again to take further screenshots etc.

SvenWollinger ***@***.***> schrieb am Do., 16. Sept. 2021,
20:23:

**Comment by SvenWollinger** [comment] 2021-09-16 21:23
Fixed :^)

**Closed by SvenWollinger** 2021-09-16 21:23 UTC
Labels: bug, High Priority
